# Generated by Django 4.2.3 on 2023-08-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMANI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amani',
            name='Desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='amani',
            name='precoAtual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
